// ─── PASTE THIS INTO YOUR data.ts ───────────────────────────────────────────
// Replace the existing HIM_QUIZ_QUESTIONS and GESD_QUIZ_QUESTIONS arrays
// Also add: import { QuizQuestion } from './types'; at the top of data.ts if not present
import { QuizQuestion } from './types';

export const HIM_QUIZ_QUESTIONS: QuizQuestion[] = [
  { id:1,  topic:"Child Rights",    question:"According to the Hero in Me curriculum, who is defined as a child?", options:["Anyone under the age of 16 years","Anyone under the age of 18 years","Anyone under the age of 21 years","Anyone under the age of 15 years"], correctAnswer:1, explanation:"A child is every human being below the age of 18 years, consistent with the UN Convention on the Rights of the Child." },
  { id:2,  topic:"Values",          question:"Which of the following is an example of a PERSONAL value?", options:["Discipline and Co-operation","Kindness and Charity","Honesty and Respect","Brotherhood and Justice"], correctAnswer:2, explanation:"Personal values guide individual growth and include honesty, responsibility, humanity, and respect. Discipline, co-operation, brotherhood, and justice are social values." },
  { id:3,  topic:"Puberty",         question:"At what age range does puberty typically begin in boys?", options:["6 to 10 years","9 to 14 years","12 to 18 years","8 to 13 years"], correctAnswer:1, explanation:"The curriculum states puberty typically occurs between 9 to 14 years for boys and 8 to 13 years for girls." },
  { id:4,  topic:"Peer Pressure",   question:"What is the best definition of peer pressure?", options:["Pressure from teachers to perform well","Feeling pressured by friends or peers to act in certain ways","Pressure from parents to follow family rules","Academic stress caused by examinations"], correctAnswer:1, explanation:"Peer pressure is the pressure felt from friends or peers to act or behave in certain ways, which can be positive or negative." },
  { id:5,  topic:"Self-Esteem",     question:"Which is NOT listed as a way to promote high self-esteem?", options:["Practice saying no","Talk to someone you trust","Compare yourself to others to improve","Avoid comparing yourself to others"], correctAnswer:2, explanation:"The curriculum teaches you should AVOID comparing yourself to others. Comparing negatively lowers self-esteem." },
  { id:6,  topic:"Hero in Me",      question:"How is Hero in Me (HIM) defined?", options:["Being physically strong and brave","Turning from Negative to Positive","Having superpowers to help others","Following rules set by adults"], correctAnswer:1, explanation:"Hero in Me is defined as Turning from Negative to Positive — difficult situations lead to positive outcomes, growth, or courage." },
  { id:7,  topic:"Assertiveness",   question:"What does being assertive mean?", options:["Being aggressive and dominating others","Staying silent to avoid conflict","Being direct, honest, and standing up for yourself","Always agreeing with what others say"], correctAnswer:2, explanation:"Assertiveness means being direct and standing up for yourself, being honest about what you need and want, without being aggressive." },
  { id:8,  topic:"Step-Up",         question:"What is the definition of Step-Up?", options:["To run away from danger","To call the police immediately","To come forward and take action to prevent or stop harm","To ignore minor conflicts"], correctAnswer:2, explanation:"Step-Up is To Come Forward — taking action to prevent, stop, or calm down a conflict situation to protect yourself or someone else." },
  { id:9,  topic:"Consent",         question:"Which best describes consent?", options:["The absence of a no from the other person","An agreement between people meaning hearing the word yes","Permission needed only once","Something only needed in romantic relationships"], correctAnswer:1, explanation:"Consent is an agreement between people. The curriculum emphasizes consent is hearing the word YES. It is NOT the absence of NO. It must happen every time." },
  { id:10, topic:"Breaking Silence", question:"What is Breaking the Silence?", options:["Shouting loudly when attacked","Posting about abuse on social media","Giving someone hope and courage to talk about a violent incident","Reporting every small argument to a teacher"], correctAnswer:2, explanation:"Breaking the Silence means giving someone hope and courage to speak about violence, harassment, or abuse they experienced or witnessed, so they can get help." },
  { id:11, topic:"Awareness",        question:"What is the first step to becoming aware according to HIM?", options:["Run away immediately","Slow down and notice small problems","Call for help loudly","Lock yourself in a safe place"], correctAnswer:1, explanation:"The curriculum teaches that slowing down helps you notice any small problem around you — this is the first step to awareness." },
  { id:12, topic:"De-escalation",    question:"What does de-escalation mean?", options:["Escalating a conflict to get attention","Calming down a conflict situation","Running away from danger","Calling authorities immediately"], correctAnswer:1, explanation:"De-escalation simply means 'Calm Down' — calmly communicating with an agitated person to understand, manage and resolve a conflict situation." },
  { id:13, topic:"Negotiation",      question:"What is the goal of negotiation according to the curriculum?", options:["To win at all costs","To separate people from the problem","To avoid all conflict","To always agree with others"], correctAnswer:1, explanation:"The goal of negotiation is to separate people from the problem — addressing issues not personalities, aiming for a win-win situation." },
  { id:14, topic:"Values",           question:"Social values are best described as:", options:["Private personal beliefs","Principles defined by society, institutions, traditions and cultural beliefs","Individual goals and ambitions","Rules set by parents and guardians"], correctAnswer:1, explanation:"Social values are a set of moral principles defined by society dynamics, institutions, traditions and cultural beliefs that enable individuals to improve their social life." },
  { id:15, topic:"Child Rights",     question:"Which of the following is a PROTECTION right?", options:["Right to play and recreation","Right to education","Right to protection from child labour","Right to freedom of expression"], correctAnswer:2, explanation:"Protection rights include the right to protection from child labour, sexual and physical abuse, drugs, and other harms." },
  { id:16, topic:"Referral",         question:"Which service provides immediate support and basic counselling for survivors?", options:["Social Welfare/NGOs","Community Victim Support Unit","Mother Group","Child Protection Worker"], correctAnswer:1, explanation:"The Community Victim Support Unit provides immediate support and basic counselling to survivors of violence." },
  { id:17, topic:"Puberty",          question:"Which of the following is a physical change during puberty in BOYS only?", options:["Growth of body hair","Acne and pimples","Growth spurts","Deepening of the voice"], correctAnswer:3, explanation:"Deepening of the voice is a physical change specific to males during puberty. Body hair, acne, and growth spurts occur in both boys and girls." },
  { id:18, topic:"Self-Esteem",      question:"What is a sign of HIGH self-esteem?", options:["Accepting nicknames like 'shorty' or 'fatty'","Giving credit to others when it belongs to you","Accepting new challenges and trying new activities","Not accepting compliments"], correctAnswer:2, explanation:"High self-esteem allows you to accept new challenges and try new activities, because you believe in yourself and your ability to succeed." },
  { id:19, topic:"Step-Up",          question:"When doing Step-Up activities, which factor should you consider?", options:["How to embarrass the attacker","Be aware of distance and know where escape routes are","Always confront the aggressor directly","Ignore bystanders around you"], correctAnswer:1, explanation:"When doing Step-Up, be aware of distance (how close to be), know escape routes, and consider if there may be allies nearby." },
  { id:20, topic:"Breaking Silence", question:"The Tithandizane Child Help Line in Malawi is:", options:["Toll-free number 116","Toll-free number 999","Number 5600","Number 0800"], correctAnswer:0, explanation:"116 is the Tithandizane Child Help Line — a free helpline available in Malawi for children experiencing abuse or violence." },
];

export const GESD_QUIZ_QUESTIONS: QuizQuestion[] = [
  { id:1,  topic:"GESD Basics",     question:"What does GESD stand for?", options:["Girls Education Self Development","Girls Empowerment Self Defense","Gender Equality Social Development","Girls Empowerment Social Direction"], correctAnswer:1, explanation:"GESD stands for Girls Empowerment Self Defense — the foundation on which all safety goals and strategies are built." },
  { id:2,  topic:"GESD Aim",        question:"According to the curriculum, what is the MAIN AIM of self-defense?", options:["To fight and win every battle","To hurt the attacker first","To get away","To show strength"], correctAnswer:2, explanation:"The main aim of GESD is TO GET AWAY. Fighting back is the last resort when you cannot get away by running or talking." },
  { id:3,  topic:"Awareness",       question:"What are the four visible signs of awareness represented by A.B.L.E?", options:["Alert Bold Loud Effective","Aware Brave Listen Escape","Alert Body Language Loudness Eye Contact","Attention Balance Look Escape"], correctAnswer:2, explanation:"A.B.L.E stands for Alert, Body Language, Loudness, Eye Contact — the four visible signs that you are aware and cannot be easily targeted." },
  { id:4,  topic:"Inner Voice",     question:"Which of the following is a MESSENGER OF THE INNER VOICE?", options:["Ridicule","Minimize","Gut feeling","Justify"], correctAnswer:2, explanation:"Gut feeling is a messenger of the inner voice. Ridicule, Minimize, and Justify are messengers of DENIAL — they silence your intuition." },
  { id:5,  topic:"APS",             question:"The three parts of the Attack Progression Scale are:", options:["Mental Physical Emotional","Verbal Intimidation Physical","Shouting Pushing Fighting","Testing Warning Attacking"], correctAnswer:1, explanation:"The APS has three levels: Verbal (hands off, irritating), Intimidation (hands off, dangerous), and Physical (hands on, life-threatening)." },
  { id:6,  topic:"Red Flags",       question:"What does it mean when an attacker ignores your No?", options:["He is being polite","It is a red flag — he will probably not hear it later either","He is shy and nervous","He simply did not hear you"], correctAnswer:1, explanation:"Ignoring No is a major RED FLAG in the Perpetrator's Progression Pattern. If he cannot hear No now, he will not hear it later." },
  { id:7,  topic:"Five Fingers",    question:"The Five Fingers of Emergency Self-Defense are:", options:["Scream Run Hide Fight Call","Think Yell Run Fight Tell","Aware Bold Loud Fight Escape","Look Listen Smell Touch Taste"], correctAnswer:1, explanation:"The Five Fingers are Think, Yell, Run, Fight, Tell. Each represents a step in the emergency self-defense strategy." },
  { id:8,  topic:"Consent",         question:"Consent is defined as:", options:["Doing what you are told","Not saying no","An agreement between people","Wearing certain clothes"], correctAnswer:2, explanation:"Consent is an agreement between people. Consent is HEARING THE WORD YES. It is NOT the absence of hearing No." },
  { id:9,  topic:"Gender",          question:"What is the difference between sex and gender?", options:["They mean exactly the same thing","Sex is biological and gender is social and cultural","Gender is biological and sex is social","Both are chosen by individuals"], correctAnswer:1, explanation:"Sex refers to biological differences — universal and unchanging. Gender refers to social differences — constructed by society and changeable." },
  { id:10, topic:"Physical Skills", question:"What should you do if you are grabbed by an attacker?", options:["Freeze and wait for help","Panic and scream","Ask the attacker why","Use What is Free and What is Open to strike vulnerable targets and get away"], correctAnswer:3, explanation:"Use 'What is Free, What is Open' — identify what body parts are free and which vulnerable targets on the attacker are open. Strike and escape." },
  { id:11, topic:"Self-Defense",    question:"What are the FOUR PRIMARY TARGETS on an attacker's body?", options:["Stomach, Back, Arms, Legs","Eyes, Throat, Groins, Knee","Ears, Nose, Chest, Feet","Head, Shoulders, Hips, Ankles"], correctAnswer:1, explanation:"The four primary targets are Eyes, Throat, Groins, and Knee — they are soft, easy to strike, and disable the attacker quickly." },
  { id:12, topic:"SMEVB",           question:"What does the V stand for in S.M.E.V.B?", options:["Victory","Vigilance","Voice","Violence"], correctAnswer:2, explanation:"V stands for Voice — up to 85% of Empowerment Training is using our voices effectively. Yell No, call for help, negotiate, distract." },
  { id:13, topic:"Assertiveness",   question:"Which response to conflict does GESD recommend?", options:["Aggressive — bullying to get your way","Assertive — direct, clear, with eye contact and upright posture","Passive — doing things you don't want because you cannot say No","Silent — avoiding all confrontation"], correctAnswer:1, explanation:"GESD recommends the assertive response: being direct, stating clearly what you want, using eye contact and upright posture. Not aggressive, not passive." },
  { id:14, topic:"Boundaries",      question:"What are boundaries?", options:["Physical walls that keep you safe","Rules we set for how we want others to speak and act towards us","Suggestions we make to others","Permission slips for activities"], correctAnswer:1, explanation:"Boundaries are rules we set for how we want others to speak and act towards us. We train people how to treat us from the moment we meet." },
  { id:15, topic:"PPP",             question:"At which stage of the Perpetrator's Progression Pattern is a victim most at risk?", options:["Stage 1 — Victim Identification","Stage 2 — Victim Selection","Stage 3 — Attack Process","All stages are equally dangerous"], correctAnswer:2, explanation:"Stage 3 — Attack Process — is the most dangerous. The attacker uses threats to position you. Any place he moves you to will be BETTER FOR HIM and WORSE FOR YOU." },
  { id:16, topic:"Breaking Silence", question:"Which of the following is an important point about Breaking the Silence?", options:["The attack is always your fault","You must speak up publicly","The attack or abuse is NOT your fault","You should keep the secret forever"], correctAnswer:2, explanation:"The attack or abuse is NOT your fault. You should tell, even if the attacker told you not to. Tell until someone believes you and helps you get the support you need." },
  { id:17, topic:"Child Rights",    question:"A child is defined as:", options:["Anyone under 16 years","Anyone under 18 years","Anyone under 21 years","Anyone in primary school"], correctAnswer:1, explanation:"A child is every human being below the age of eighteen years, consistent with the UN Convention on the Rights of the Child." },
  { id:18, topic:"Awareness",       question:"Which of the following describes an UNAWARE person?", options:["Someone who makes eye contact","Someone walking confidently","Someone listening to music with headphones","Someone standing tall with shoulders back"], correctAnswer:2, explanation:"Someone listening to music with headphones is an example of an unaware person — they cannot perceive their surroundings, making them an easier target." },
  { id:19, topic:"Menstruation",    question:"What is the average menstrual cycle length?", options:["14 days","28 days","45 days","7 days"], correctAnswer:1, explanation:"The average menstrual cycle is every 28 days. Cycles from 21 to 35 days are also considered normal." },
  { id:20, topic:"Referral",        question:"The Malawi GBV Crisis Line number is:", options:["116","999","5600 / 6600","0800"], correctAnswer:2, explanation:"5600 / 6600 is the GBV Crisis Line in Malawi. 116 is the Tithandizane Child Help Line. Both are important helpline numbers to know." },
];
